# -*- coding: utf-8 -*-
"""FinanceStudy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xrfi9ubivlj-YdKNqm9mwgG54p4cNqpm
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Stock price data (Manually entered for now, as data is haphazardly added in the assignment xlsx)
data = {
    "Date": range(1, 26),  # Assuming 25 days of stock data
    "Godrej": [811, 808.1, 828.7, 849.4, 870.05, 875, 880.05, 877.55, 895.55, 876.15, 878.3, 870.25, 844.5, 806, 815.05, 854, 872.95, 868.85, 895.3, 914, 923.35, 928.45, 943.95, 941.45, 950],
    "Abbot": [28286.05, 28254.15, 29050, 29187.25, 29066.85, 27784.65, 25998.55, 25950, 25757.2, 25808.25, 26000, 25611, 25260.2, 25500, 26481, 27236.55, 27600, 27449, 27600, 27450, 27362.6, 27134.45, 27700.2, 28170.5, 28200.2],
    "Interglobe": [4329, 4200.6, 4276, 4287.3, 4340, 4367.25, 4368.85, 4295, 4340, 4285, 4196.3, 4182.2, 4230, 4189, 4061, 4125.65, 4000, 3946.4, 3985, 4090.6, 4069.65, 4065.65, 3995.6, 3951, 3953.75],
    "TajGVK": [387.15, 379.5, 376.6, 400.3, 411.3, 421.05, 422.35, 409.25, 365.2, 343, 349, 353, 339, 330.6, 338.8, 360.5, 362.75, 360, 374, 389.2, 388.6, 382.95, 367.05, 357.2, 360.55],
    "Kaveri_Seed": [924.35, 922.25, 924.05, 936.6, 951.05, 925.2, 921.5, 924, 940.05, 922.05, 895, 899, 877.25, 879.1, 862.15, 882.8, 906.05, 907.9, 898.8, 896.05, 891.6, 897.15, 881, 851.1, 878]
}

df = pd.DataFrame(data)
df

df.set_index("Date", inplace=True)
df

returns = df.pct_change().dropna()
print(returns)

"""the volatility of the stocks will be

"""

volatility = returns.std()
print(volatility)

plt.figure(figsize=(12, 6))
plt.plot(volatility)
plt.xlabel("Stocks")
plt.ylabel("Volatility")
plt.title("volatiles visualized")
plt.legend()
plt.grid(True)
plt.show()

"""lets plot stock prizes"""

plt.figure(figsize=(12, 6))
for col in returns.columns:
    plt.plot(returns.index, returns[col], label=col)
plt.xlabel("Days")
plt.ylabel("Daily returns")
plt.title("Daily returns of the selected companies")
plt.legend(df.columns)
plt.grid(True)
plt.show()

"""simple portfolio of equal weightage of each stock"""

simp_port_return = returns.mean(axis=1)
print(simp_port_return)

"""lets plot our portfolio returns over time"""

plt.figure(figsize=(12,6))
plt.plot(simp_port_return.index, simp_port_return, marker='o', linestyle='-', color='b', label="Daily Portfolio Return")
plt.axhline(y=0, color='r', linestyle='--')  # zero return at the red dotted line
plt.xlabel("Days")
plt.ylabel("Daily Return")
plt.title("Daily Portfolio Returns Over Time")
plt.legend()
plt.show()

"""what about cumulative returns?"""

c_returns = (simp_port_return + 1).cumprod()
print(c_returns)

plt.figure(figsize=(12,6))
plt.plot(c_returns.index, c_returns, marker='o', linestyle='-', color='g', label="Cumulative Portfolio Growth")
plt.axhline(y=c_returns.mean(), color='r', linestyle='--')  # mean return at the red dotted line
plt.xlabel("Days")
plt.ylabel("Portfolio Value (Normalized)")
plt.title("Cumulative Portfolio Growth Over Time")
plt.legend()
plt.show()

"""lets compare our simple portfolio to a market index"""

import yfinance as yf

ticker = '^NSEI'
m_data = yf.download(ticker, period="1mo", interval="1d")  #last month of daily data
m_data = m_data["Close"]
print(m_data)

m_data["Date"] = range(1, len(m_data) + 1)
m_data.set_index("Date", inplace=True)
print(m_data)

"""we have data for only 19 days, lets drop 20 - 25 from portfolio"""

df = df.iloc[:19]
df

market_return = m_data.pct_change().dropna()
print(market_return)

c_m_returns = (1 + market_return).cumprod()

plt.figure(figsize=(12,6))
plt.plot(c_returns.index, c_returns, marker='o', linestyle='-', color='b', label="Portfolio Cumulative Growth")
plt.plot(c_m_returns.index, c_m_returns , marker='o', linestyle='--', color='r', label="Market Index (NIFTY 50) Growth")
plt.xlabel("Date")
plt.ylabel("Cumulative Return")
plt.title("Portfolio vs. NIFTY 50 Performance")
plt.legend()
plt.show()

"""as expected, although it might have initially outpeformed the market, our portfolio isnt as competitive - similiar peak to NIFTY 50 in the end, but the risks are much more adverse for our portfolio. our portfolio is also more volatile with a more haphazard curve"""